/* Generated By:JavaCC: Do not edit this line. Proyecto1.java */
package uniandes.teolen.parserJavaCC.Proyecto1;
import java.util.*;
public class Proyecto1 implements Proyecto1Constants {
        ArrayList < String > variables = new ArrayList<String>();
        ArrayList < String > sitios = new ArrayList<String>();
        ArrayList < String > transiciones = new ArrayList<String>();

  final public void pRed() throws ParseException, Error {
    jj_consume_token(P_RED);
    jj_consume_token(NOMBRE);
    label_1:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case VAR:
        ;
        break;
      default:
        jj_la1[0] = jj_gen;
        break label_1;
      }
      var();
    }
    label_2:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case SITIO:
        ;
        break;
      default:
        jj_la1[1] = jj_gen;
        break label_2;
      }
      sitio();
    }
    label_3:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case TRANSICION:
        ;
        break;
      default:
        jj_la1[2] = jj_gen;
        break label_3;
      }
      transicion();
    }
    label_4:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case ARCO:
        ;
        break;
      default:
        jj_la1[3] = jj_gen;
        break label_4;
      }
      arco();
    }
    jj_consume_token(FIN_RED);
  }

  final public void var() throws ParseException, Error {
 Token t1;
    jj_consume_token(VAR);
    t1 = jj_consume_token(NOMBRE);
    jj_consume_token(IGUAL);
    jj_consume_token(num);
   boolean encontrado = false;
   for(int i = 0; i<variables.size() && !encontrado; i++) {
     if(variables.get(i).equals(t1.image)) {
      encontrado = true;
 } }
   if(encontrado) { {if (true) throw new Error("La variable ya se encontraba declarada previamente :c");} }
   else {  variables.add(t1.image); }
  }

  final public void sitio() throws ParseException {
 Token t1; Token v; String variable;
    jj_consume_token(SITIO);
    jj_consume_token(DOS_PUNTOS);
    t1 = jj_consume_token(NOMBRE);
   boolean encontrado = false;
   for(int i = 0; i<sitios.size() && !encontrado; i++) {
     if(sitios.get(i).equals(t1.image)) {
       encontrado = true;
   }
   if(encontrado) { {if (true) throw new Error("El sitio ya se encontraba declarada previamente :c");} }
   else { sitios.add(t1.image); }
   }
    jj_consume_token(CAPACIDAD);
    jj_consume_token(DOS_PUNTOS);
    jj_consume_token(IGUAL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case num:
      jj_consume_token(num);
      break;
    case NOMBRE:
      verificarVar();
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
      case MULTIPLY:
      case DIVIDE:
        switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
        case PLUS:
          jj_consume_token(PLUS);
          break;
        case MINUS:
          jj_consume_token(MINUS);
          break;
        case MULTIPLY:
          jj_consume_token(MULTIPLY);
          break;
        case DIVIDE:
          jj_consume_token(DIVIDE);
          break;
        default:
          jj_la1[4] = jj_gen;
          jj_consume_token(-1);
          throw new ParseException();
        }
        verificarVar();
        break;
      default:
        jj_la1[5] = jj_gen;
        ;
      }
      break;
    default:
      jj_la1[6] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
    jj_consume_token(MARCACION);
    jj_consume_token(DOS_PUNTOS);
    jj_consume_token(IGUAL);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case num:
      jj_consume_token(num);
      break;
    case CAPACIDAD:
      jj_consume_token(CAPACIDAD);
      break;
    default:
      jj_la1[7] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void transicion() throws ParseException {
 Token t; Token t1;
    jj_consume_token(TRANSICION);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case NOMBRE:
      t = jj_consume_token(NOMBRE);
    //Solo crea transiciones si no existen antes. 
   boolean encontrado1 = false;
   for(int i = 0; i<transiciones.size() && !encontrado1; i++) {
     if(transiciones.get(i).equals(t.image)) {
       encontrado1 = true;
   }
   if(encontrado1) { {if (true) throw new Error("La transicion ya se encontraba declarada previamente :c");} }
   else { transiciones.add(t.image); }
   }
      break;
    case AP:
      jj_consume_token(AP);
      t1 = jj_consume_token(NOMBRE);
   //Solo crea transiciones si no existen antes. 
   boolean encontrado = false;
   for(int i = 0; i<transiciones.size() && !encontrado; i++) {
     if(transiciones.get(i).equals(t1.image)) {
       encontrado = true;
   }
   if(encontrado) { {if (true) throw new Error("La transicion ya se encontraba declarada previamente :c");} }
   else { transiciones.add(t1.image); }
   }
      jj_consume_token(COMA);
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case EXPONENCIAL:
        jj_consume_token(EXPONENCIAL);
        jj_consume_token(COMA);
        dobleParametro();
        break;
      case DETERMINISTICO:
        jj_consume_token(DETERMINISTICO);
        jj_consume_token(COMA);
        parametro();
        break;
      case UNIFORME:
        jj_consume_token(UNIFORME);
        jj_consume_token(COMA);
        dobleParametro();
        break;
      default:
        jj_la1[8] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      jj_consume_token(CP);
      break;
    default:
      jj_la1[9] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  final public void dobleParametro() throws ParseException {
    parametro();
    jj_consume_token(COMA);
    parametro();
  }

  final public void parametro() throws ParseException {
    exp();
  }

  final public void arco() throws ParseException {
    jj_consume_token(ARCO);
    jj_consume_token(AP);
    if (jj_2_1(2)) {
      arcoEntrando();
    } else {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case NOMBRE:
        arco2();
        break;
      default:
        jj_la1[10] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
    jj_consume_token(CP);
  }

  final public void arcoEntrando() throws ParseException {
 Token t1; Token t2; Token t3;
    t3 = jj_consume_token(NOMBRE);
    jj_consume_token(DOS_PUNTOS);
    t1 = jj_consume_token(NOMBRE);
    jj_consume_token(COMA);
    t2 = jj_consume_token(NOMBRE);
    Boolean sitio1 = false;
    Boolean sitio2 = false;
    Boolean transicion1 = false;
    Boolean transicion2 = false;

      boolean encontrado1 = false;
   for(int i = 0; i<transiciones.size() && !encontrado1; i++) {
     if(transiciones.get(i).equals(t1.image)) {
       encontrado1 = true;
       transicion1=true;
   }
   if(!encontrado1) { {if (true) throw new Error("La variable no existe :'v");} }
   }

   for(int i = 0; i<sitios.size() && !encontrado1; i++) {
     if(sitios.get(i).equals(t1.image)) {
       encontrado1 = true;
       sitio1=true;
   }
   if(!encontrado1) { {if (true) throw new Error("La variable no existe :'v");} }
 }

 boolean encontrado2 = false;
   for(int i = 0; i<transiciones.size() && !encontrado2; i++) {
     if(transiciones.get(i).equals(t2.image)) {
       encontrado2 = true;
       transicion2=true;
   }
   if(!encontrado2) { {if (true) throw new Error("La variable no existe :'v");} }
   }

   for(int i = 0; i<sitios.size() && !encontrado2; i++) {
     if(sitios.get(i).equals(t2.image)) {
       encontrado2 = true;
       sitio2=true;
   }
   if(!encontrado2) { {if (true) throw new Error("La variable no existe :'v");} }
 }


 if((sitio1&&sitio2)||(transicion1&&transicion2))
 {
{if (true) throw new Error("No puede haber arcos entre dos elementos del mismo tipo.");}
 }
  }

  final public void arco2() throws ParseException {
 Token t1; Token t2;
    t1 = jj_consume_token(NOMBRE);
    jj_consume_token(COMA);
    t2 = jj_consume_token(NOMBRE);
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case COMA:
      jj_consume_token(COMA);
      parametro();
      break;
    default:
      jj_la1[11] = jj_gen;
      ;
    }
    boolean sitio1 = false;
    boolean sitio2 = false;
    boolean transicion1 = false;
    boolean transicion2 = false;

      boolean encontrado1 = false;
   for(int i = 0; i<transiciones.size() && !encontrado1; i++) {
     if(transiciones.get(i).equals(t1.image)) {
       encontrado1 = true;
       transicion1=true;
   }
   if(!encontrado1) { {if (true) throw new Error("La transicion no existe");} }
   }

   for(int i = 0; i<sitios.size() && !encontrado1; i++) {
     if(sitios.get(i).equals(t1.image)) {
       encontrado1 = true;
       sitio1=true;
   }
   if(!encontrado1) { {if (true) throw new Error("La variable no existe");} }
 }

 boolean encontrado2 = false;
   for(int i = 0; i<transiciones.size() && !encontrado2; i++) {
     if(transiciones.get(i).equals(t2.image)) {
       encontrado2 = true;
       transicion2=true;
   }
   if(!encontrado2) { {if (true) throw new Error("La variable no existe");} }
   }

   for(int i = 0; i<sitios.size() && !encontrado2; i++) {
     if(sitios.get(i).equals(t2.image)) {
       encontrado2 = true;
       sitio2=true;
   }
   if(!encontrado2) { {if (true) throw new Error("La variable no existe");} }
 }


 if((sitio1&&sitio2)||(transicion1&&transicion2))
 {
{if (true) throw new Error("No puede haber arcos entre dos elementos del mismo tipo.");}
 }
  }

  final public void verificarVar() throws ParseException {
 Token t;
    t = jj_consume_token(NOMBRE);

  boolean encontrado = false;
  boolean esNumber = false;
   try {
     if(t.image.equals("Inf"))
     {
       {if (true) return;}
     }
  double d = Double.parseDouble( t.image );
  esNumber =  true;
        }catch(Exception e ) {
  esNumber =  false;
        }
        if(!esNumber) {
   for(int i = 0; i<variables.size() && !encontrado; i++) {
     if(variables.get(i).equals(t.image)) {
       encontrado = true;
   } }
   if(!encontrado) { {if (true) throw new Error("La variable " + t.image + " no existe");} }
    }
  }

  final public void exp() throws ParseException {
    term();
    label_5:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
      case MINUS:
        ;
        break;
      default:
        jj_la1[12] = jj_gen;
        break label_5;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case PLUS:
        jj_consume_token(PLUS);
        term();
        break;
      case MINUS:
        jj_consume_token(MINUS);
        term();
        break;
      default:
        jj_la1[13] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void term() throws ParseException {
    fact();
    label_6:
    while (true) {
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
      case DIVIDE:
        ;
        break;
      default:
        jj_la1[14] = jj_gen;
        break label_6;
      }
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case MULTIPLY:
        jj_consume_token(MULTIPLY);
        fact();
        break;
      case DIVIDE:
        jj_consume_token(DIVIDE);
        fact();
        break;
      default:
        jj_la1[15] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
    }
  }

  final public void fact() throws ParseException {
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case MINUS:
      jj_consume_token(MINUS);
      break;
    default:
      jj_la1[16] = jj_gen;
      ;
    }
    switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
    case num:
    case NOMBRE:
      switch ((jj_ntk==-1)?jj_ntk():jj_ntk) {
      case num:
        jj_consume_token(num);
        break;
      case NOMBRE:
        verificarVar();
        break;
      default:
        jj_la1[17] = jj_gen;
        jj_consume_token(-1);
        throw new ParseException();
      }
      break;
    case AP:
      jj_consume_token(AP);
      exp();
      jj_consume_token(CP);
      break;
    default:
      jj_la1[18] = jj_gen;
      jj_consume_token(-1);
      throw new ParseException();
    }
  }

  private boolean jj_2_1(int xla) {
    jj_la = xla; jj_lastpos = jj_scanpos = token;
    try { return !jj_3_1(); }
    catch(LookaheadSuccess ls) { return true; }
    finally { jj_save(0, xla); }
  }

  private boolean jj_3R_7() {
    if (jj_scan_token(NOMBRE)) return true;
    if (jj_scan_token(DOS_PUNTOS)) return true;
    return false;
  }

  private boolean jj_3_1() {
    if (jj_3R_7()) return true;
    return false;
  }

  /** Generated Token Manager. */
  public Proyecto1TokenManager token_source;
  SimpleCharStream jj_input_stream;
  /** Current token. */
  public Token token;
  /** Next token. */
  public Token jj_nt;
  private int jj_ntk;
  private Token jj_scanpos, jj_lastpos;
  private int jj_la;
  private int jj_gen;
  final private int[] jj_la1 = new int[19];
  static private int[] jj_la1_0;
  static {
      jj_la1_init_0();
   }
   private static void jj_la1_init_0() {
      jj_la1_0 = new int[] {0x4000,0x800000,0x400000,0x200000,0x1e0,0x1e0,0x88000000,0x8040000,0x38000,0x80001000,0x80000000,0x800,0x60,0x60,0x180,0x180,0x40,0x88000000,0x88001000,};
   }
  final private JJCalls[] jj_2_rtns = new JJCalls[1];
  private boolean jj_rescan = false;
  private int jj_gc = 0;

  /** Constructor with InputStream. */
  public Proyecto1(java.io.InputStream stream) {
     this(stream, null);
  }
  /** Constructor with InputStream and supplied encoding */
  public Proyecto1(java.io.InputStream stream, String encoding) {
    try { jj_input_stream = new SimpleCharStream(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source = new Proyecto1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream) {
     ReInit(stream, null);
  }
  /** Reinitialise. */
  public void ReInit(java.io.InputStream stream, String encoding) {
    try { jj_input_stream.ReInit(stream, encoding, 1, 1); } catch(java.io.UnsupportedEncodingException e) { throw new RuntimeException(e); }
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor. */
  public Proyecto1(java.io.Reader stream) {
    jj_input_stream = new SimpleCharStream(stream, 1, 1);
    token_source = new Proyecto1TokenManager(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(java.io.Reader stream) {
    jj_input_stream.ReInit(stream, 1, 1);
    token_source.ReInit(jj_input_stream);
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Constructor with generated Token Manager. */
  public Proyecto1(Proyecto1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  /** Reinitialise. */
  public void ReInit(Proyecto1TokenManager tm) {
    token_source = tm;
    token = new Token();
    jj_ntk = -1;
    jj_gen = 0;
    for (int i = 0; i < 19; i++) jj_la1[i] = -1;
    for (int i = 0; i < jj_2_rtns.length; i++) jj_2_rtns[i] = new JJCalls();
  }

  private Token jj_consume_token(int kind) throws ParseException {
    Token oldToken;
    if ((oldToken = token).next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    if (token.kind == kind) {
      jj_gen++;
      if (++jj_gc > 100) {
        jj_gc = 0;
        for (int i = 0; i < jj_2_rtns.length; i++) {
          JJCalls c = jj_2_rtns[i];
          while (c != null) {
            if (c.gen < jj_gen) c.first = null;
            c = c.next;
          }
        }
      }
      return token;
    }
    token = oldToken;
    jj_kind = kind;
    throw generateParseException();
  }

  static private final class LookaheadSuccess extends java.lang.Error { }
  final private LookaheadSuccess jj_ls = new LookaheadSuccess();
  private boolean jj_scan_token(int kind) {
    if (jj_scanpos == jj_lastpos) {
      jj_la--;
      if (jj_scanpos.next == null) {
        jj_lastpos = jj_scanpos = jj_scanpos.next = token_source.getNextToken();
      } else {
        jj_lastpos = jj_scanpos = jj_scanpos.next;
      }
    } else {
      jj_scanpos = jj_scanpos.next;
    }
    if (jj_rescan) {
      int i = 0; Token tok = token;
      while (tok != null && tok != jj_scanpos) { i++; tok = tok.next; }
      if (tok != null) jj_add_error_token(kind, i);
    }
    if (jj_scanpos.kind != kind) return true;
    if (jj_la == 0 && jj_scanpos == jj_lastpos) throw jj_ls;
    return false;
  }


/** Get the next Token. */
  final public Token getNextToken() {
    if (token.next != null) token = token.next;
    else token = token.next = token_source.getNextToken();
    jj_ntk = -1;
    jj_gen++;
    return token;
  }

/** Get the specific Token. */
  final public Token getToken(int index) {
    Token t = token;
    for (int i = 0; i < index; i++) {
      if (t.next != null) t = t.next;
      else t = t.next = token_source.getNextToken();
    }
    return t;
  }

  private int jj_ntk() {
    if ((jj_nt=token.next) == null)
      return (jj_ntk = (token.next=token_source.getNextToken()).kind);
    else
      return (jj_ntk = jj_nt.kind);
  }

  private java.util.List<int[]> jj_expentries = new java.util.ArrayList<int[]>();
  private int[] jj_expentry;
  private int jj_kind = -1;
  private int[] jj_lasttokens = new int[100];
  private int jj_endpos;

  private void jj_add_error_token(int kind, int pos) {
    if (pos >= 100) return;
    if (pos == jj_endpos + 1) {
      jj_lasttokens[jj_endpos++] = kind;
    } else if (jj_endpos != 0) {
      jj_expentry = new int[jj_endpos];
      for (int i = 0; i < jj_endpos; i++) {
        jj_expentry[i] = jj_lasttokens[i];
      }
      jj_entries_loop: for (java.util.Iterator<?> it = jj_expentries.iterator(); it.hasNext();) {
        int[] oldentry = (int[])(it.next());
        if (oldentry.length == jj_expentry.length) {
          for (int i = 0; i < jj_expentry.length; i++) {
            if (oldentry[i] != jj_expentry[i]) {
              continue jj_entries_loop;
            }
          }
          jj_expentries.add(jj_expentry);
          break jj_entries_loop;
        }
      }
      if (pos != 0) jj_lasttokens[(jj_endpos = pos) - 1] = kind;
    }
  }

  /** Generate ParseException. */
  public ParseException generateParseException() {
    jj_expentries.clear();
    boolean[] la1tokens = new boolean[32];
    if (jj_kind >= 0) {
      la1tokens[jj_kind] = true;
      jj_kind = -1;
    }
    for (int i = 0; i < 19; i++) {
      if (jj_la1[i] == jj_gen) {
        for (int j = 0; j < 32; j++) {
          if ((jj_la1_0[i] & (1<<j)) != 0) {
            la1tokens[j] = true;
          }
        }
      }
    }
    for (int i = 0; i < 32; i++) {
      if (la1tokens[i]) {
        jj_expentry = new int[1];
        jj_expentry[0] = i;
        jj_expentries.add(jj_expentry);
      }
    }
    jj_endpos = 0;
    jj_rescan_token();
    jj_add_error_token(0, 0);
    int[][] exptokseq = new int[jj_expentries.size()][];
    for (int i = 0; i < jj_expentries.size(); i++) {
      exptokseq[i] = jj_expentries.get(i);
    }
    return new ParseException(token, exptokseq, tokenImage);
  }

  /** Enable tracing. */
  final public void enable_tracing() {
  }

  /** Disable tracing. */
  final public void disable_tracing() {
  }

  private void jj_rescan_token() {
    jj_rescan = true;
    for (int i = 0; i < 1; i++) {
    try {
      JJCalls p = jj_2_rtns[i];
      do {
        if (p.gen > jj_gen) {
          jj_la = p.arg; jj_lastpos = jj_scanpos = p.first;
          switch (i) {
            case 0: jj_3_1(); break;
          }
        }
        p = p.next;
      } while (p != null);
      } catch(LookaheadSuccess ls) { }
    }
    jj_rescan = false;
  }

  private void jj_save(int index, int xla) {
    JJCalls p = jj_2_rtns[index];
    while (p.gen > jj_gen) {
      if (p.next == null) { p = p.next = new JJCalls(); break; }
      p = p.next;
    }
    p.gen = jj_gen + xla - jj_la; p.first = token; p.arg = xla;
  }

  static final class JJCalls {
    int gen;
    Token first;
    int arg;
    JJCalls next;
  }

}
