/* Generated By:JavaCC: Do not edit this line. Proyecto1Constants.java */
package uniandes.teolen.parserJavaCC.Proyecto1;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface Proyecto1Constants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int DOS_PUNTOS = 9;
  /** RegularExpression Id. */
  int IGUAL = 10;
  /** RegularExpression Id. */
  int COMA = 11;
  /** RegularExpression Id. */
  int AP = 12;
  /** RegularExpression Id. */
  int CP = 13;
  /** RegularExpression Id. */
  int VAR = 14;
  /** RegularExpression Id. */
  int UNIFORME = 15;
  /** RegularExpression Id. */
  int EXPONENCIAL = 16;
  /** RegularExpression Id. */
  int DETERMINISTICO = 17;
  /** RegularExpression Id. */
  int CAPACIDAD = 18;
  /** RegularExpression Id. */
  int MARCACION = 19;
  /** RegularExpression Id. */
  int holi = 20;
  /** RegularExpression Id. */
  int ARCO = 21;
  /** RegularExpression Id. */
  int TRANSICION = 22;
  /** RegularExpression Id. */
  int SITIO = 23;
  /** RegularExpression Id. */
  int P_RED = 24;
  /** RegularExpression Id. */
  int FIN_RED = 25;
  /** RegularExpression Id. */
  int DIGIT = 26;
  /** RegularExpression Id. */
  int num = 27;
  /** RegularExpression Id. */
  int LETRAMAY = 28;
  /** RegularExpression Id. */
  int LETRAMIN = 29;
  /** RegularExpression Id. */
  int LETRA = 30;
  /** RegularExpression Id. */
  int NOMBRE = 31;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"+\"",
    "\"-\"",
    "\"*\"",
    "\"/\"",
    "\":\"",
    "\"=\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"VAR\"",
    "\"Uniforme\"",
    "\"Exponencial\"",
    "\"Deterministico\"",
    "\"capacidad\"",
    "\"marcacion_i\"",
    "\"holi\"",
    "\"ARCO\"",
    "\"TRANSICION\"",
    "\"SITIO\"",
    "\"P_RED\"",
    "\"FIN_RED\"",
    "<DIGIT>",
    "<num>",
    "<LETRAMAY>",
    "<LETRAMIN>",
    "<LETRA>",
    "<NOMBRE>",
  };

}
