/* Generated By:JavaCC: Do not edit this line. QuizPracticoConstants.java */
package uniandes.teolen.parserJavaCC.QuizPractico;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface QuizPracticoConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PLUS = 5;
  /** RegularExpression Id. */
  int MINUS = 6;
  /** RegularExpression Id. */
  int MULTIPLY = 7;
  /** RegularExpression Id. */
  int DIVIDE = 8;
  /** RegularExpression Id. */
  int INT = 9;
  /** RegularExpression Id. */
  int VOID = 10;
  /** RegularExpression Id. */
  int RETURN = 11;
  /** RegularExpression Id. */
  int AP = 12;
  /** RegularExpression Id. */
  int CP = 13;
  /** RegularExpression Id. */
  int COMA = 14;
  /** RegularExpression Id. */
  int PYC = 15;
  /** RegularExpression Id. */
  int DP = 16;
  /** RegularExpression Id. */
  int AC = 17;
  /** RegularExpression Id. */
  int CC = 18;
  /** RegularExpression Id. */
  int PUSH = 19;
  /** RegularExpression Id. */
  int PUSH_FROM = 20;
  /** RegularExpression Id. */
  int POP = 21;
  /** RegularExpression Id. */
  int POP_TO = 22;
  /** RegularExpression Id. */
  int TIMES = 23;
  /** RegularExpression Id. */
  int POW = 24;
  /** RegularExpression Id. */
  int CHS = 25;
  /** RegularExpression Id. */
  int IDX = 26;
  /** RegularExpression Id. */
  int num = 27;
  /** RegularExpression Id. */
  int DIGIT = 28;
  /** RegularExpression Id. */
  int LETRAMAY = 29;
  /** RegularExpression Id. */
  int LETRAMIN = 30;
  /** RegularExpression Id. */
  int LETRA = 31;
  /** RegularExpression Id. */
  int nombre = 32;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"PLUS\"",
    "\"MINUS\"",
    "\"*\"",
    "\"/\"",
    "\"INT\"",
    "\"VOID\"",
    "\"RETURN\"",
    "\"(\"",
    "\")\"",
    "\",\"",
    "\";\"",
    "\":\"",
    "\"< \"",
    "\" >\"",
    "\"PUSH\"",
    "\"PUSH_FROM\"",
    "\"POP\"",
    "\"POP_TO\"",
    "\"TIMES\"",
    "\"POW\"",
    "\"CHS\"",
    "<IDX>",
    "<num>",
    "<DIGIT>",
    "<LETRAMAY>",
    "<LETRAMIN>",
    "<LETRA>",
    "<nombre>",
  };

}
