/* Generated By:JavaCC: Do not edit this line. ParserPrologConstants.java */
package uniandes.teolen.parserJavaCC.myParserDR;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ParserPrologConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ASIGNAR = 5;
  /** RegularExpression Id. */
  int DECLARAR = 6;
  /** RegularExpression Id. */
  int MINUS = 7;
  /** RegularExpression Id. */
  int OPERACION = 8;
  /** RegularExpression Id. */
  int COMIENZO = 9;
  /** RegularExpression Id. */
  int CIERRE = 10;
  /** RegularExpression Id. */
  int VARIABLE = 11;
  /** RegularExpression Id. */
  int SITIO = 12;
  /** RegularExpression Id. */
  int CAPACIDAD = 13;
  /** RegularExpression Id. */
  int MARCACION = 14;
  /** RegularExpression Id. */
  int TRANSICION = 15;
  /** RegularExpression Id. */
  int UNIOEXP = 16;
  /** RegularExpression Id. */
  int DET = 17;
  /** RegularExpression Id. */
  int ARC = 18;
  /** RegularExpression Id. */
  int DIGIT = 19;
  /** RegularExpression Id. */
  int NUMERO = 20;
  /** RegularExpression Id. */
  int PALABRA = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\":=\"",
    "\"=\"",
    "\"-\"",
    "<OPERACION>",
    "\"P_RED\"",
    "\"FIN_RED\"",
    "\"VAR\"",
    "\"SITIO\"",
    "\"capacidad\"",
    "\"marcacion_i\"",
    "\"TRANSICION\"",
    "<UNIOEXP>",
    "\"Deterministico\"",
    "\"ARCO\"",
    "<DIGIT>",
    "<NUMERO>",
    "<PALABRA>",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\",\"",
  };

}
